import { CalcFieldsOD } from './calc-utils';

interface ODPresetItem {
  readonly presetName: string;
  readonly presetInputs: CalcFieldsOD;
}

export const odPresets: readonly ODPresetItem[] = Object.freeze([
  {
    presetName: '自定义',
    presetInputs: {
      hit: 0,
      hitCountUp: 0,
      fixedOD: 0,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '通用 3 Hit',
    presetInputs: {
      hit: 3,
      hitCountUp: 0,
      fixedOD: 0,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '大海不良分子',
    presetInputs: {
      hit: 6,
      hitCountUp: 0,
      fixedOD: 50,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '大海不良分子 (抵抗)',
    presetInputs: {
      hit: 6,
      hitCountUp: 0,
      fixedOD: 50,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: true,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '巨大炸裂者 (6跟班)',
    presetInputs: {
      hit: 10,
      hitCountUp: 6,
      fixedOD: 0,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '无色子弹+',
    presetInputs: {
      hit: 5,
      hitCountUp: 0,
      fixedOD: 30,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '哀伤的雪花莲 (破盾)',
    presetInputs: {
      hit: 2,
      hitCountUp: 0,
      fixedOD: 150,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '哀伤的雪花莲 (破盾&抵抗)',
    presetInputs: {
      hit: 2,
      hitCountUp: 0,
      fixedOD: 150,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: true,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '豪迈! 海盗加农炮 (1目标)',
    presetInputs: {
      hit: 5,
      hitCountUp: 10,
      fixedOD: 0,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '豪迈! 海盗加农炮 (2目标)',
    presetInputs: {
      hit: 5,
      hitCountUp: 3,
      fixedOD: 0,
      numTarget: 2,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '豪迈! 海盗加农炮 (3目标)',
    presetInputs: {
      hit: 5,
      hitCountUp: 1,
      fixedOD: 0,
      numTarget: 3,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '苍焰螺旋',
    presetInputs: {
      hit: 10,
      hitCountUp: 0,
      fixedOD: 0,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '苍焰螺旋(2目标)',
    presetInputs: {
      hit: 10,
      hitCountUp: 0,
      fixedOD: 0,
      numTarget: 2,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '梦幻泡影',
    presetInputs: {
      hit: 9,
      hitCountUp: 0,
      fixedOD: 0,
      numTarget: 1,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '冰冻圆舞曲 (2目标)',
    presetInputs: {
      hit: 12,
      hitCountUp: 3,
      fixedOD: 0,
      numTarget: 2,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '寒冰斩 (2目标&梅雨)',
    presetInputs: {
      hit: 3,
      hitCountUp: 5,
      fixedOD: 0,
      numTarget: 2,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
  {
    presetName: '觉醒的思维 (2目标&梅雨)',
    presetInputs: {
      hit: 10,
      hitCountUp: 5,
      fixedOD: 0,
      numTarget: 2,
      earrings: 15,
      isBaboo: false,
      isResisted: false,
      otherBuff: 0,
      odRate: 100,
    },
  },
]);
